const ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  UPDATE_FORM_VALUES: 'UPDATE_FORM_VALUES',
  COMPLETE_BPMS_TASK: 'COMPLETE_BPMS_TASK',
  SET_BPMS_ASSIGNEE: 'SET_BPMS_ASSIGNEE',
  INSTANCE_SAVED: 'INSTANCE_SAVED',
  INSTANCE_CREATED: 'INSTANCE_CREATED',
  INSTANCE_SUBMITTED: 'INSTANCE_SUBMITTED'
}

module.exports = {
  ACTIONS
}
